### ISSUE TITLE
[headshop] Revamp

### ISSUE THREAD

**Issue by MrBlizzard** [MrBlizzard/RCAdmins-Tracker#77] opened 2018-05-16 06:33 UTC
Bulk listed below v

**Comment by MrBlizzard** [comment] 2018-05-19 07:53
Headshop2 and pokeheadshop2 are now on 1-9, you can place an npc down and bind either of those menus to test and avoid the cd for it.

**Comment by LothMoria** [comment] 2018-05-19 16:35
Could not test Gold Head

All other heads required placing, breaking, then placing again to show up
All heads except orange, iron, squid, and companion cube went back to steve heads after a little bit

**Comment by LothMoria** [comment] 2018-05-19 16:45
Pixelmon headshop:
Required placing, breaking, then replacing to show up
Cubone head went back to steve head after a bit

**Comment by LothMoria** [comment] 2018-05-19 16:55
Update on Pixelmon Headshop:
All but snorlax and charjabug have turned back to steve

**Comment by MrBlizzard** [comment] 2018-05-19 20:53
what do you mean by "turned back to steve"

**Comment by LothMoria** [comment] 2018-05-20 15:03
So, they showed up as what they're supposed to be in my inventory, but upon first placing them, they appeared as steve heads on the wall. After breaking and replacing them, they showed up as what they're supposed to be. A little bit after they were left alone, they showed the steve texture again, but this time also had the steve skin when broken, and replacing them didn't help after that point

**Comment by MrBlizzard** [comment] 2018-05-21 05:07
This is for every single head?

**Comment by PhantomWolf42** [comment] 2018-05-23 23:33
Player heads often jump back and forth between Steve/Alex and their intended skins. If the head is received properly when the command is run I believe it's a working skin. On occasion my own player head displays as Alex, but mostly is my own.

**Comment by PhantomWolf42** [comment] 2018-05-26 08:29
After testing, found that the heads of online players are generated instantly, and can be placed with the correct skins without having to break and replace.

Using the heads of offline players has a minute delay, and when placed are Steve/Alex, and must be broken and replaced to match the correct head.

After a full MC Launcher crash, I rejoined P1 to find a series of heads that were Alex (players never been on RC) had reverted to their correct heads. Left P1, went to P1 Test Server where all heads were working.

Connected back to live P1 without closing MC to find 2 heads reverted to Alex/Steve. Heads of offline players jalby and MrBlizzard. Strangely, LilyMu's head remained intact despite being offline. Disconnected from RC, returned to the P1 Test Server where all heads remained working. Returned to live P1 to find heads as they were earlier (all fine except jalby and MrBlizzard)

Completely closed Minecraft. Rejoined live P1 to find all heads working, except jalby and MrBlizzard. A copy of jalby's head that had been donated to myself (and worked fine until testing) now suddenly is Alex, matching up with the test head. My copy of LilyMu's existing head also never broke before/after testing.

**Comment by MrBlizzard** [comment] 2018-05-26 10:02
Perms for goldblock head have been corrected

**Comment by PhantomWolf42** [comment] 2018-05-26 10:32
Testing headshop2 on Pixel 4 (seems my wall of Heads on P1 confirmed all my testing would be invalid).

Worked on first placement: Apple, Melon, Eye of Ender, Ghast (already had a ghast head equipped), Iron, Bowling (but quickly reverted to alex), Dispenser, Clock, Companion Cube, Squid, Absol, Cubone, Wailord, Magikarp, Charjabug, Turtwig, Latias, Bisharp, Snorlax

Tried Ghast head on P3. Placed as Alex, broken then placed again correctly.

Failed on first placement: Magma, Orange, Gold, Dice, Wolverine
Worked on second placement: Magma, Orange, Gold, Dice, Wolverine

Stormtrooper head is now Assassin's Creed head

**Comment by MrBlizzard** [comment] 2018-07-14 08:35
Due to the glitchiness of heads, we are postponing the revamps to headshop until they are less likely to glitch out. 

Reassigned to low priority

**Comment by MrBlizzard** [comment] 2018-10-02 02:16
This is still buggy, can some more tests be had to judge the severity? If it's not terribly severe, we are going to make a Halloween Headshop.

**Closed** 2018-11-08 14:07 UTC
Labels: Back Burner, awaiting completion, enhancement, priority:low
